### ISSUE TITLE
Entitetene ikke tilgjengelig. Feilmelding: list index out of range

### ISSUE THREAD

**Issue by magne74** [sindrebroch/ha-elvia#11]
Hei.

Fikk plutselig denne etter å ha oppdatert til siste core-versjon som 2023.3.0. Også Tibber-integrasjonen gikk ned. Hentet tilbake tidligere versjon, men fortsatt feil. Forsøkt å legge inn integrasjon på nytt. Hjalp ikke. Tibber kom tilbake.

**Comment by sindrebroch** [comment]
Hei! Takk for innmelding!

Har samme feil selv, skal se på det ved anledning. Ut fra feilmeldingen kan det virke som at den ikke klarer å hente ut max-timene. Mulig dette er relatert til endring i APIet, eller eventuelt at dataene ser litt rare ut ved månedsskifte.

**Comment by sindrebroch** [comment]
@magne74 Det funker for meg etter å ha oppdatert til 2023.3.1. Hva med deg?

Litt usikker på om det skyldes månedsskifte eller versjon, men det finner vi nok ut på sikt.

**Comment by magne74** [comment]
Kan bekrefte at alt er ok etter samme oppgradering. Mvh MagneSendt fra min iPhone3. mar. 2023 kl. 16:22 skrev Sindre Broch ***@***.***>:﻿
@magne74 Det funker for meg etter å ha oppdatert til 2023.3.1. Hva med deg?
Litt usikker på om det skyldes månedsskifte eller versjon, men det finner vi nok ut på sikt.

**Comment by grlarsen** [comment]
Får samme feil etter restart i kveld. Logg som følger:

//
Unexpected error fetching elvia data: list index out of range
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 239, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/elvia/coordinator.py", line 80, in _async_update_data
    await self.map_maxhour_values(self.maxhours)
  File "/config/custom_components/elvia/coordinator.py", line 105, in map_maxhour_values
    "1": self.getMonth(aggregateMonth, 2),
  File "/config/custom_components/elvia/coordinator.py", line 92, in getMonth
    "value": object['maxHours'][index]['value'],
IndexError: list index out of range
//

**Comment by sindrebroch** [comment]
@grlarsen Takk for innmelding! Kan virke som at den sliter litt ved månedsskifte ja. Skal ha det i bakhodet neste gang jeg kikker på koden 👍

**Comment by LTKingChaos** [comment]
Hos meg så stoppet det opp 16.00 den 02.04 og kom igang igjen 06.00 03.04

**Comment by LaStrada** [comment]
Sliter med dette i dag. Jeg har i dag 2 objekter i denne listen, ikke 3. Antageligvis fordi det er den 2. i dag. Så det må legges til noe feilhåndtering her når det er <3 objekter
https://github.com/sindrebroch/ha-elvia/blob/9e3e86d2d76b1bec3612e1c06e93bd807e09e86e/custom_components/elvia/coordinator.py#LL102C58-L102C75

Responsen min (sensurert litt) fra maxhours endepunktet:

```JSON
{
    "meteringpoints": [
        {
            "meteringPointId": "xxx",
            "customerContract": {
                "startDate": "2019-12-16T00:00:00+01:00",
                "endDate": null
            },
            "maxHoursCalculatedTime": "2023-06-02T09:55:23+02:00",
            "maxHoursFromTime": "2023-05-01T00:00:00+02:00",
            "maxHoursToTime": "2023-06-02T09:00:00+02:00",
            "maxHoursAggregate": [
                {
                    "averageValue": 1.1765,
                    "maxHours": [
                        {
                            "startTime": "2023-06-02T02:00:00+02:00",
                            "endTime": "2023-06-02T03:00:00+02:00",
                            "value": 0.654,
                            "uom": "kWh",
                            "noOfMonthsBack": 0,
                            "production": false,
                            "verified": false
                        },
                        {
                            "startTime": "2023-06-01T12:00:00+02:00",
                            "endTime": "2023-06-01T13:00:00+02:00",
                            "value": 1.699,
                            "uom": "kWh",
                            "noOfMonthsBack": 0,
                            "production": false,
                            "verified": true
                        }
                    ],
                    "uom": "kWh",
                    "noOfMonthsBack": 0
                },
                {
                    "averageValue": 2.3819999999999997,
                    "maxHours": [
                        {
                            "startTime": "2023-05-05T14:00:00+02:00",
                            "endTime": "2023-05-05T15:00:00+02:00",
                            "value": 2.31,
                            "uom": "kWh",
                            "noOfMonthsBack": 1,
                            "production": false,
                            "verified": true
                        },
                        {
                            "startTime": "2023-05-28T12:00:00+02:00",
                            "endTime": "2023-05-28T13:00:00+02:00",
                            "value": 2.396,
                            "uom": "kWh",
                            "noOfMonthsBack": 1,
                            "production": false,
                            "verified": true
                        },
                        {
                            "startTime": "2023-05-08T13:00:00+02:00",
                            "endTime": "2023-05-08T14:00:00+02:00",
                            "value": 2.44,
                            "uom": "kWh",
                            "noOfMonthsBack": 1,
                            "production": false,
                            "verified": true
                        }
                    ],
                    "uom": "kWh",
                    "noOfMonthsBack": 1
                }
            ]
        }
    ]
}
```

**Comment by LaStrada** [comment]
Sweet, ser ut som om [siste beta](https://github.com/sindrebroch/ha-elvia/releases/tag/0.3.0b1) funker! Returnerer nå 0 istedenfor å krasje Takk 🎉

**Comment by sindrebroch** [comment]
Knall! Lukker denne 👍
