### ISSUE TITLE
New exposed values

### ISSUE THREAD

**Issue by mar-eid** [sindrebroch/ha-elvia#3]
Hi,

I saw you requested suggestions for values to expose to HA.

Below is a list of values that I fetch from Elvia by rest-sensor and use.

Form: 
 `/customer/metervalues/api/v2/maxhours`
Params:
` calculateTime: `first day of next month (e.g. if September ,then 2022-10-01)

Used parameters:
```
state: meteringpoints[0].maxHoursAggregate[0].maxHours[0]
attributes:
  - startTime
  - endTime
  - uom
  - verified

state: meteringpoints[0].maxHoursAggregate[0].maxHours[1]
attributes:
  - startTime
  - endTime
  - uom
  - verified
  - 
state: meteringpoints[0].maxHoursAggregate[0].maxHours[3]
attributes:
  - startTime
  - endTime
  - uom
  - verified
  - 
state: meteringpoints[0].maxHoursAggregate[0].averageValue
attributes:
  - maxHoursCalculatedTime
  - maxHoursFromTime
  - maxHoursToTime
  - maxHoursAggregate
```
 All the above values are used to graph current cost threshold

Form: 
`/grid-tariff/digin/api/1/tariffquery/meteringpointsgridtariffs`
payload:
```
{
  range: today/tomorrow
  meteringPointIds: myId
}
```

Used parameters:

```
state: gridTariffCollections[0].gridTariff.tariffPrice.hours[n].total
attributes:
 - hours
```
The state is the current hour value from the today query.

The `hours` attribute is the complete array/json

By combining today/tomorrow query, it is possible to make graph trend together with Tibber values, reflecting what you actually pay for the power.

**Comment by sindrebroch** [comment]
This is great, thanks for the recommendations. I will try adding some of these at my next sit-down

**Comment by sindrebroch** [comment]
New sensors added in latest release

**Comment by mar-eid** [comment]
> 

Tanks alot! 🥇
