### ISSUE TITLE
Forbruksledd feil?

### ISSUE THREAD

**Issue by kjetilpp** [sindrebroch/ha-elvia#4]
Lurer på om jeg misforstår noe, eller så er forbruksleddet feil. HA viser 0,431 NOK/kWh mens Elvia sier Energileddet er 35,29øre/kWh nå på dagen, eller er ikke de to tingene det samme?

**Comment by sindrebroch** [comment]
Tror det er noe rusk der ja. Har hatt litt problemer med APIet hver gang jeg skal sette meg ned å kikke på det, men skal kikke på det en gang 👍

**Comment by sindrebroch** [comment]
@kjetilpp Er det fortsatt feil? Det kan virke som at appen viser gjennomsnittspris for døgnet, mens integrasjonen rapporterer times-verdi. Jeg tror det stemmer hos meg, men tar gjerne imot innspill hvis det ikke stemmer...

**Comment by sindrebroch** [comment]
Lukker denne grunnet manglende respons. Mulig dette har blitt fikset underveis, eller feilen var skyldt trøbbel i APIet. 

Gjerne gjenåpne hvis feilen fortsatt oppstår.
