### ISSUE TITLE
Update every hour instead of one hour after start

### ISSUE THREAD

**Issue by mariwing** [sindrebroch/ha-elvia#6]
Hi, thank you for the great work on this. It saved me a lot of time so i did not have to create this myself :-)

What would have been great (if possible, I have not programmed much against Home Assistant before) was if the component updated one minute after each new hour. This would make the "forbruksledd" more accurate since as far as I can tell the data is now updated once every hour after a restart of Home Assistant so the "forbruksledd" is delayed when it is changing.

**Comment by sindrebroch** [comment]
Absolutely, I have been thinking the same thing. Requires me getting to know the scheduling in homeassistant a bit better, thats why I left it like it was, but I will implement this at some point. Whenever I sit back down with it

Also contributions are welcome 👍

**Comment by sindrebroch** [comment]
New update-functionality has been implemented in the latest release.
