### ISSUE TITLE
Array of all prices for today (and maybe tomorrow)

### ISSUE THREAD

**Issue by mariwing** [sindrebroch/ha-elvia#7]
I am using the Nordpool component (https://github.com/custom-components/nordpool) for fetching spot prices. That integration have an array of the price for each hour. It would be simpler to compute total cost of electricity if this component did the same. I find the entire utility meter/tariff/cost tracking in Home Assistant to be poorly designed and not really suited for a price scheme that changes each hour but I have still managed to get energy price per hour. If the "nettleie" was also available in such an array it would be easy to include that as well in my setup.

**Comment by sindrebroch** [comment]
Not a bad idea, thanks for the suggestion. I'll think about it, but I think there are a lot of improvements to the integration that comes before this. I'm also a bit worried about the possible issues that comes with including another datasource, but these might be small.

Also, contributions are welcome 👍

**Comment by sindrebroch** [comment]
The `sensor.energy_price` now has an attribute `Daily tariff`, which contains the tariffs for today. Is this in a usable format?

**Comment by ChristopherSkarsethstuen** [comment]
Hi Sindre

This is great, but the data under daily_tariff attribute seems to be off by one hour
It starts at todays date at 01.00 and ends at tomorrows date at 01.00 
but should start at todays date at 00.00 and end at tomorrows date at 00.00

**Comment by sindrebroch** [comment]
Will look at this at some point, but I think that is what is returned directly from the API for that date. Might be reporting different timezones? Have you checked how it relates to the times when the values change?

**Comment by ChristopherSkarsethstuen** [comment]
Now it is 2 hours wrong. Starting at todays date 02.00 and ending at tomorrows date at 02.00  (changed after DST?)
The prices seems to be correct for the actual time. The two first hours are just missing

**Comment by sindrebroch** [comment]
I have updated the returned values in the latest release. Please reopen if it does not work properly
