### ISSUE TITLE
Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups

### ISSUE THREAD

**Issue by odechr** [sindrebroch/ha-elvia#8]
Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. 
Please report issue to the custom integration author for elvia using this method at custom_components/elvia/__init__.py, line 40: hass.config_entries.async_setup_platforms(entry, PLATFORMS)

**Comment by sindrebroch** [comment]
Thanks for reporting, will try to get it updated before 2023.3-release.

**Comment by sindrebroch** [comment]
This has been fixed in the latest release.
